### ISSUE TITLE
How do i make same connection as IFTT.com?

### ISSUE THREAD

**Issue by fotoKrille** [eyefi/cloud-api-doc#10]
Hi how do i make same request and auth for user as IFTT.com?

Also is it posible to att hooks? Like eyefi push notifications to my server?

**Comment by kimgust** [comment]
We don't currently support webhooks, web-flow oauth, or push notifications to third party apps, although we may in the coming months. I'll update this if/when we do.

**Comment by fotoKrille** [comment]
Ok, have ifttt.com a special non public api to access eye-fi cloud?
We would love to implement it to our service.
