### ISSUE TITLE
Simple Example help for Newbie

### ISSUE THREAD

**Issue by narfmm** [eyefi/cloud-api-doc#8]
I apologize in advance if this is the wrong place to put this.  I am trying to develop for EyeFi, JavaScript.  Going through the examples, I can get the "Pet Store" example to work (Doggie under ID=2).  But when I attempt to .add authorization, Node says there is an error at .add.  I have a token from EyeFi.  Tried several versions of the .add construct, all fail at .add.  Node version = 0.12.2, Swagger version = 2.1.2-M2 (from npm install).  I am mainly an Android developer, but this is something I need to understand.  Is the Python version a better route?  Any help is greatly appreciated.  Thank you.

Specific error -> windows.clientAuthorizations.add('key', ...
Type Error:  Cannot read property 'add' of undefined Object ...

Code:
var window = require("swagger-client")

window.clientAuthorization.add('key', new ApiKeyAuthorization('api_key','Bearer ACCESS_TOKEN', 'header'));

var swagger = new client.SwaggerApi({
  url: 'https://api.eyefi.com/3/swagger/1.2/api-docs',
  success: function() {
    if(swagger.ready === true) {
      swagger.apis.events.getEvents();
    }
  }
});

**Comment by kimgust** [comment]
If you are using Node, try following [this example](https://github.com/eyefi/eyefi-js#usage) exactly and let me know how it goes.

**Comment by narfmm** [comment]
Hi kimgust, 

Thank you very much for your reply.  I am mainly an Android developer, so probably doing something wrong.  This is Windows 8.1, through a command line.  

So, I put the code in a file called try.js, then just type node try.js 

The example without .add works fine.

I tried doing exactly the sample (not including the npm, that gives an error) as you recommended.  With and without the TOKEN string from EyeFi (~50 characters).  Gives error.

I do npm install swagger-client from the cmd line before, and it has a little spinner action, so I hope I'm OK with that.  Windows puts swagger in the path (C:\user\me\appdata\roaming\npm-cache), where as Node.js is in c:\program files\node.js , and there are modules in there.

Do I need the swagger module to be in the Node.js directory?  I would think that with it is in the path it should find it.

The specific error ->
**path**\try.js
clientauthorization.add('key', new client.ApiAuthorization('Authorization
                             ^
TypeError: Cannot read property 'add' of undefined
   at Object.<anonymus> <**path**\try.js:3:22>
   at Module._compile <module.js:460:26>
   at Object.Module_extensions..js <module.js:478:10>
   at Module.load <module.js:355:32>
   at Function.Module._load <module.js:310:12>
   at Function.Module.runMain <module.js:501:10>
   at startup <node.js:129:16>
   at node.js:814:3

Thank you for your help.  I looks around Stackoverflow, but this combination (EyeFi and Swagger) is pretty new.  [at Object.Module_extensions..js has 2 dots]

**Comment by kimgust** [comment]
It doesn't look like you're trying the example exactly as is. The example shows `client.authorizations.add`.

**Comment by narfmm** [comment]
Hi kimgust.  Yes, just a typo on my part, here is the exact try.js.  It is a direct copy and paste from the example:

var client = require("swagger-client")

client.authorizations.add('key', new client.ApiKeyAuthorization('Authorization', 'Bearer TOKEN', 'header'));

var swagger = new client.SwaggerApi({
  url: 'https://api.eyefi.com/3/swagger/1.2/api-docs',
  success: function() {
    if(swagger.ready === true) {
      swagger.apis.albums.getAlbums();
    }
  }
});

**Comment by kimgust** [comment]
If you are still getting errors they must be different since your code has changed. My suggestion at this point is to try the example in the official [swagger-js](/swagger-api/swagger-js) library, and if you still have problems file an issue there for help. If you can get that one to work, and still have issues with ours, then file an issue in our [eyefi-js](/eyefi/eyefi-js) repo so others searching for help with our Javascript SDK will benefit.

**Comment by narfmm** [comment]
My code did not change, only my error posting.  The client.authorizations.add was always correct.  As I mentioned originally, I got the:

var client = require("swagger-client")

var swagger = new client({
  url: 'http://petstore.swagger.io/v2/swagger.json',
  success: function() {
    swagger.apis.pet.getPetById({petId:1});
  }
});

example to work, just had to change petID to 2, 1 gave an error.  I guess I will try Python

**Comment by kimgust** [comment]
Ah right, ok. I took another quick look at the swagger-js library and our example isn't working for me either. I'll dig into this later today. I'll open an issue in our eyefi-js repo which is a better home for this and reference this issue. Thanks for reporting.

**Comment by narfmm** [comment]
Thank you.  Appreciate your help.

**Comment by narfmm** [comment]
Dear kimgust, your update did the trick!  Thank you so much!  I'm so glad I haven't lost my mind, yet.
